### PR TITLE
Setup

### PR DESCRIPTION
**Pull request by SKairinos**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-sso/3)

### CODE REVIEW

**Review by SKairinos — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-sso/3)* status: 0 of 36 files reviewed, 2 unresolved discussions

___
*[`backend/service/settings.py` line 50 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-sso/3#-NenIV2nCYMndw1GY_Vk:-NenIV2nCYMndw1GY_Vl:b-5ln16d) ([raw file](https://github.com/ocadotechnology/codeforlife-sso/blob/ba679e7f07cf60d74da13a70de90c3da12419c95/backend/service/settings.py#L50)):*
> ```Python
> ]
> 
> ROOT_URLCONF = "service.urls"
> ```

make reusable settings

**Review by SKairinos — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-sso/3)* status: 0 of 36 files reviewed, 3 unresolved discussions

___
*[`backend/service/settings.py` line 68 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-sso/3#-NenI_-I3V5d2hpbrdeQ:-NenI_-I3V5d2hpbrdeR:b-lgs3j4) ([raw file](https://github.com/ocadotechnology/codeforlife-sso/blob/ba679e7f07cf60d74da13a70de90c3da12419c95/backend/service/settings.py#L68)):*
> ```Python
> ]
> 
> WSGI_APPLICATION = "service.wsgi.application"
> ```

reusable setting

**Review by SKairinos — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-sso/3)* status: 0 of 36 files reviewed, 4 unresolved discussions

___
*[`backend/service/settings.py` line 83 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-sso/3#-NenIy3DDeMSHKw8UAey:-NenIy3DDeMSHKw8UAez:b-lgs3j4) ([raw file](https://github.com/ocadotechnology/codeforlife-sso/blob/ba679e7f07cf60d74da13a70de90c3da12419c95/backend/service/settings.py#L83)):*
> ```Python
> # https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators
> 
> AUTH_PASSWORD_VALIDATORS = [
> ```

reusable setting

**Review by SKairinos — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-sso/3)* status: 0 of 36 files reviewed, 4 unresolved discussions

___
*[`backend/service/settings.py` line 83 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-sso/3#-NenIy3DDeMSHKw8UAey:-NenJ89p3mrfeXcWcDG3:bme505o) ([raw file](https://github.com/ocadotechnology/codeforlife-sso/blob/ba679e7f07cf60d74da13a70de90c3da12419c95/backend/service/settings.py#L83)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

reusable setting
</blockquote></details>

add TODO to create custom password validators

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> Reviewed 36 of 36 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-sso/3)* status: all files reviewed, 8 unresolved discussions (waiting on @SKairinos)

___
*[`.github/workflows/main.yaml` line 28 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-sso/3#-NengY5E3ggdnxMJCWbM:-NengY5E3ggdnxMJCWbN:b-615vr3) ([raw file](https://github.com/ocadotechnology/codeforlife-sso/blob/ba679e7f07cf60d74da13a70de90c3da12419c95/.github/workflows/main.yaml#L28)):*
> ```YAML
>         with:
>           python-version: ${{ env.PYTHON_VERSION }}
>       
> ```

Extra whitespaces
___
*[`backend/api/forms.py` line 69 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-sso/3#-NenHVGzC23y0-hmKEOG:-NenhERZAKnq4YfCjDgE:bsoodxz) ([raw file](https://github.com/ocadotechnology/codeforlife-sso/blob/ba679e7f07cf60d74da13a70de90c3da12419c95/backend/api/forms.py#L69)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

validate 5 characters
</blockquote></details>

Reminder
___
*[`backend/api/urls.py` line 15 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-sso/3#-NeniSeJ9HlMxqkGQ7uE:-NeniSeKBDoQlhTklAN-:bx6z7o7) ([raw file](https://github.com/ocadotechnology/codeforlife-sso/blob/ba679e7f07cf60d74da13a70de90c3da12419c95/backend/api/urls.py#L15)):*
> ```Python
>                     name="login",
>                 ),
>                 path(
> ```

Is there a reason why this URL path isn't in `cron` like the other cron jobs are in the portal-react and portal repos?
___
*[`backend/api/views.py` line 59 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-sso/3#-NenhhdK1oUZxvYdXWQH:-NenhhdK1oUZxvYdXWQI:bz6h8fc) ([raw file](https://github.com/ocadotechnology/codeforlife-sso/blob/ba679e7f07cf60d74da13a70de90c3da12419c95/backend/api/views.py#L59)):*
> ```Python
>         session_objects: SessionManager = Session.objects
> 
>         before_session_count = session_objects.all().count()
> ```

Learnt this just the other day but it seems like you can just do `session_objects.count()` and it's the same :man_shrugging: https://docs.djangoproject.com/en/3.2/ref/models/querysets/#count
___
*[`backend/api/views.py` line 66 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-sso/3#-Neni2QD1pZOm_Dzj8ob:-Neni2QD1pZOm_Dzj8oc:buo9nmt) ([raw file](https://github.com/ocadotechnology/codeforlife-sso/blob/ba679e7f07cf60d74da13a70de90c3da12419c95/backend/api/views.py#L66)):*
> ```Python
>         call_command("clearsessions")
> 
>         after_session_count = session_objects.all().count()
> ```

Same here
___
*[`backend/service/settings.py` line 50 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-sso/3#-NenIV2nCYMndw1GY_Vk:-NeniJ7bBv2ms_CArz6f:bsoodxz) ([raw file](https://github.com/ocadotechnology/codeforlife-sso/blob/ba679e7f07cf60d74da13a70de90c3da12419c95/backend/service/settings.py#L50)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

make reusable settings
</blockquote></details>

Reminder
___
*[`backend/service/settings.py` line 68 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-sso/3#-NenI_-I3V5d2hpbrdeQ:-NeniMmn8ja1fpkv6WR7:bsoodxz) ([raw file](https://github.com/ocadotechnology/codeforlife-sso/blob/ba679e7f07cf60d74da13a70de90c3da12419c95/backend/service/settings.py#L68)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

reusable setting
</blockquote></details>

Reminder
___
*[`backend/service/settings.py` line 83 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-sso/3#-NenIy3DDeMSHKw8UAey:-NeniOEEAuhCadOOjfJP:bsoodxz) ([raw file](https://github.com/ocadotechnology/codeforlife-sso/blob/ba679e7f07cf60d74da13a70de90c3da12419c95/backend/service/settings.py#L83)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

add TODO to create custom password validators
</blockquote></details>

Reminder

**Review by SKairinos — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-sso/3)* status: all files reviewed, 7 unresolved discussions (waiting on @faucomte97)

___
*[`.github/workflows/main.yaml` line 28 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-sso/3#-NengY5E3ggdnxMJCWbM:-Ner6QDo0p1pqxLkhY_U:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-sso/blob/ba679e7f07cf60d74da13a70de90c3da12419c95/.github/workflows/main.yaml#L28)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Extra whitespaces
</blockquote></details>

Done.
___
*[`backend/api/urls.py` line 15 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-sso/3#-NeniSeJ9HlMxqkGQ7uE:-NerN4GZ1I6en2rkn00T:b2xvq14) ([raw file](https://github.com/ocadotechnology/codeforlife-sso/blob/ba679e7f07cf60d74da13a70de90c3da12419c95/backend/api/urls.py#L15)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Is there a reason why this URL path isn't in `cron` like the other cron jobs are in the portal-react and portal repos?
</blockquote></details>

Yes. It's part of a larger conversation I wanted to have about we organise our backend code. Basically, I want to organise all urls to be more object-oriented and have the following naming convention:

https://www.codeforlife.education/{service_name}/{object_name}/{function_name}/

For example, to create a new Game in the kurono service:
POST https://www.codeforlife.education/kurono/game/


So because we're mutating session objects:
GET (should be post but google requires get) https://www.codeforlife.education/sso/session/clear-expired/

**Review by SKairinos — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-sso/3)* status: all files reviewed, 4 unresolved discussions (waiting on @faucomte97)

___
*[`backend/api/urls.py` line 15 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-sso/3#-NeniSeJ9HlMxqkGQ7uE:-NerXC_y8s6vtV86-twm:b-klqlk3) ([raw file](https://github.com/ocadotechnology/codeforlife-sso/blob/ba679e7f07cf60d74da13a70de90c3da12419c95/backend/api/urls.py#L15)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

Yes. It's part of a larger conversation I wanted to have about we organise our backend code. Basically, I want to organise all urls to be more object-oriented and have the following naming convention:

https://www.codeforlife.education/{service_name}/{object_name}/{function_name}/

For example, to create a new Game in the kurono service:
POST https://www.codeforlife.education/kurono/game/


So because we're mutating session objects:
GET (should be post but google requires get) https://www.codeforlife.education/sso/session/clear-expired/
</blockquote></details>

*
GET (should be DELETE but google requires GET) https://www.codeforlife.education/sso/session/clear-expired/
___
*[`backend/api/views.py` line 59 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-sso/3#-NenhhdK1oUZxvYdXWQH:-NerQxAbBaqLLhDSlXdM:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-sso/blob/ba679e7f07cf60d74da13a70de90c3da12419c95/backend/api/views.py#L59)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Learnt this just the other day but it seems like you can just do `session_objects.count()` and it's the same :man_shrugging: https://docs.djangoproject.com/en/3.2/ref/models/querysets/#count
</blockquote></details>

Done.
___
*[`backend/api/views.py` line 66 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-sso/3#-Neni2QD1pZOm_Dzj8ob:-NerQxk00bXhHp88AUP2:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-sso/blob/ba679e7f07cf60d74da13a70de90c3da12419c95/backend/api/views.py#L66)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Same here
</blockquote></details>

Done.

**Pull request merged**
