### PR TITLE
2fa flow

### PR DESCRIPTION
**Pull request by SKairinos**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-sso/9)

### CODE REVIEW

**Review by faucomte97 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-sso/9#-:-NflEI_QCzLwlAu_2iCg:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SKairinos)

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-sso/9)* status: all files reviewed, 1 unresolved discussion (waiting on @SKairinos)

___
*[`backend/api/tests/test_views.py` line 19 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-sso/9#-NgYLM2v9Z0Gbv8XCEPN:-NgYLM2v9Z0Gbv8XCEPO:b-iu7gcc) ([raw file](https://github.com/ocadotechnology/codeforlife-sso/blob/ce2fb7a03de2a0234a04f426b160de18bfbc846f/backend/api/tests/test_views.py#L19)):*
> ```Python
>     def _get_session_auth_factors(self, response: HttpResponse):
>         cookie = response.cookies["sessionid_httponly_false"].value
>         return [af for af in cookie.split(",") if af != ""]
> ```

Please de-simplify

**Review by SKairinos — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-sso/9)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @faucomte97)

___
*[`backend/api/tests/test_views.py` line 19 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-sso/9#-NgYLM2v9Z0Gbv8XCEPN:-NgYqCFs7iV205Ef6A_G:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-sso/blob/ce2fb7a03de2a0234a04f426b160de18bfbc846f/backend/api/tests/test_views.py#L19)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Please de-simplify
</blockquote></details>

Done.

**Review by faucomte97 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-sso/9#-:-NgYt3xgBCzardMUDVIN:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @SKairinos)

**Review by faucomte97 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-sso/9)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SKairinos)

**Pull request merged**
